# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"


In [ ]:
s = "Hi there Sam!"
xx = s.split()
print(xx)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = " The diameter of Earth "
diameter = " is 12742 kilometers "
print(planet + diameter.format())


 The diameter of Earth  is 12742 kilometers 


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

'hello'

In [ ]:
print("hello")

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
DineshAlone=np.ones(10)*5
print(DineshAlone)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [ ]:
array=np.arange(20,35,2)
print(array)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a, b), axis=0)


array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd

df = {'col_1': [0, 1, 2, 3],
          'col_2': [4, 5, 6, 7]}
df = pd.DataFrame(df)
print(df)


   col_1  col_2
0      0      4
1      1      5
2      2      6
3      3      7


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
import pandas as pd
dRan1 = pd.date_range(start ='1-1-2023',
           end ='10-01-2023', freq ='M')

  
print(dRan1)

DatetimeIndex(['2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30',
               '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31',
               '2023-09-30'],
              dtype='datetime64[ns]', freq='M')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:

import pandas as pd
arr= np.arraylists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df=pd.DataFrame(arr)
print(df)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
